name: Deploy React + Vite to Github Pages

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository
            - name: Chekcout code
              uses: actions/checkout@v4
            
            # Setup Nodejs
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            # Install dependencies
            - name: Install Dependencies
              run: npm install

            # Bujild the project
            - name: Build project
              run: npm run build

            #Deploy to github pages
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: dist
